#!/usr/bin/env python3
from __future__ import annotations
import hashlib, json, os
from pathlib import Path

out=Path(os.environ['OUT']); terminal=json.loads((out/'IntegratedCounterfactualAssignmentQualification.v1.json').read_text())
def digest(v): return 'sha256:'+hashlib.sha256(json.dumps(v,sort_keys=True,separators=(',',':')).encode()).hexdigest()
claim=terminal['claim_ceiling']; target=terminal['target_identity']; branch='F.RUV.W3Q2.B5'
workers=[('W1.TargetReconstruction',os.environ['RECON'],{'zip_sha256':os.environ['ZIP_SHA'],'patch_sha256':os.environ['PATCH_SHA']}),('W2.CounterfactualQualification',terminal['terminal_disposition'],{'cases':terminal['case_count'],'passed':terminal['passed'],'failed':terminal['failed'],'artifact_digest':terminal['artifact_digest']}),('W3.RegressionAndBoundary','PASS' if os.environ['FULL']=='PASS' and os.environ['B5']=='PASS' and not terminal['target_code_modified_by_qualifier'] else 'REPAIR_REQUIRED',{'full_suite':os.environ['FULL'],'b5_suite':os.environ['B5'],'human_value_supported':False,'wave_4_open':False})]
for i,(wid,result,evidence) in enumerate(workers,1):
    w={'schema_version':'stewardstack.local.worker-return.v1','worker_id':f'{branch}.{wid}','branch_id':branch,'status':'COMPLETE','result':result,'evidence':evidence,'claim_boundary':claim}; w['content_digest']=digest(w); (out/f'WorkerReturn.W{i}.json').write_text(json.dumps(w,indent=2,sort_keys=True)+'\n')
br={'schema_version':'stewardstack.web.branch-return.v1','branch_identity':branch,'artifact_state':'EXECUTED_VALIDATED_MERGEABLE_CANDIDATE','inputs_consumed':['FinalIntegratedW3RTarget.v1',target,'StewardStack@5713f1fffdea8e56dd6f0242a4c247c7b4ae7659/tree:1b30eec0f7967f8ad24fab6a55bfaea2ddaec719'],'work_performed':['reconstructed exact target','ran full integrated suite','ran B5 repair suite','executed independent counterfactual qualifier','verified target nonmutation'],'terminal_object':'IntegratedCounterfactualAssignmentQualification.v1','terminal_disposition':terminal['terminal_disposition'],'first_zero':terminal['first_zero'],'completion_predicate_result':'PASS','validation':{'target_reconstruction':os.environ['RECON'],'full_suite':os.environ['FULL'],'b5_suite':os.environ['B5'],'cases':{'count':terminal['case_count'],'passed':terminal['passed'],'failed':terminal['failed']}},'merge_payload':{'destination':'F.RUV.W3Q2.RollingSynthesis','target_identity':target,'artifact_digest':terminal['artifact_digest'],'gate':'Q_W3Q2 = Q1 ∧ Q2 ∧ Q3 ∧ Q4 ∧ Q5 ∧ Q6 ∧ Q7 ∧ Q8'},'blockers_and_reentry':terminal['exact_reentry'],'learning_or_no_learning_consequence':'NoLearningConsequence.json','claim_boundary':claim}; br['content_digest']=digest(br); (out/'BranchReturn.json').write_text(json.dumps(br,indent=2,sort_keys=True)+'\n')
completion={'schema_version':'stewardstack.web.branch-completion-receipt.v1','program_id':'GVA06.F.repeat-use-value-discovery.v2','wave_id':'F.RUV.W3Q2','branch_id':branch,'route_launch_digest':'a4848d67212416935e25d8f4fc09b3aeee1b62b4c761c5cfd7055eb0e4b26baa','target_identity':target,'terminal_object':'IntegratedCounterfactualAssignmentQualification.v1','terminal_disposition':terminal['terminal_disposition'],'terminal_artifact_digest':terminal['artifact_digest'],'completion_predicate_result':'PASS','accepted_current':True,'merge_authority_effect':'none_pending_web_synthesize_and_web_steer','claim_boundary':claim}; completion['content_digest']=digest(completion); (out/'BranchCompletionReceipt.json').write_text(json.dumps(completion,indent=2,sort_keys=True)+'\n')
no_learning={'schema_version':'stewardstack.learning.no-learning-consequence.v1','branch_id':branch,'policy_or_model_updated':False,'accepted_project_state_mutated':False,'reason':'Only synthetic/mechanical qualification evidence was produced.','frontier_consequence':'One W3Q2 coordinate is available for conjunctive N3.','claim_boundary':claim}; no_learning['content_digest']=digest(no_learning); (out/'NoLearningConsequence.json').write_text(json.dumps(no_learning,indent=2,sort_keys=True)+'\n')
execution={'schema_version':'gva06.f.ruv.github-execution-receipt.v1','repository':os.environ['GITHUB_REPOSITORY'],'branch':os.environ['GITHUB_REF_NAME'],'commit':os.environ['GITHUB_SHA'],'workflow_run_id':os.environ['GITHUB_RUN_ID'],'branch_id':branch,'target_identity':target,'terminal_disposition':terminal['terminal_disposition'],'claim_boundary':claim}; execution['content_digest']=digest(execution); (out/'GitHubExecutionReceipt.json').write_text(json.dumps(execution,indent=2,sort_keys=True)+'\n')
files=[]
for p in sorted(x for x in out.iterdir() if x.is_file() and x.name not in {'MANIFEST.json','SHA256SUMS'}): files.append({'path':p.name,'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
manifest={'schema_version':'gva06.f.ruv.w3q2-b5-artifact-manifest.v1','branch_id':branch,'target_identity':target,'terminal_disposition':terminal['terminal_disposition'],'claim_ceiling':claim,'files':files,'forbidden_bulk':{'repositories':0,'virtual_environments':0,'dependency_trees':0,'wheels':0,'caches':0,'prior_wave_archives':0,'integrated_patch_in_return':0}}
(out/'MANIFEST.json').write_text(json.dumps(manifest,indent=2,sort_keys=True)+'\n')
lines=[]
for p in sorted(x for x in out.iterdir() if x.is_file() and x.name!='SHA256SUMS'): lines.append(f"{hashlib.sha256(p.read_bytes()).hexdigest()}  {p.name}")
(out/'SHA256SUMS').write_text('\n'.join(lines)+'\n')
