#!/usr/bin/env python3
"""Pointer-slim execution of F.RUV.W4C.B5."""
from __future__ import annotations
import argparse, hashlib, json, os
from datetime import datetime
from pathlib import Path

PROGRAM='GVA06.F.repeat-use-value-discovery.v2'; WAVE='F.RUV.W4C'; BRANCH='F.RUV.W4C.B5'
PRIOR='F.RUV.W4.B5'; TARGET='sha256:b7d3d67c4d812fc28ffed2408fa41c96367fb99ce5cc1a6de77d5658709a6d9a'
TREE='f29aa877f9df61df447ed07d51c89364bc017e5ad161d8661202084b9ee250cf'; ARCHIVE='cc3b56e6e984809fc5f8f803788bfa52c9ffc53709618ce358917bf1d30fedf2'
ROUTE='a4848d67212416935e25d8f4fc09b3aeee1b62b4c761c5cfd7055eb0e4b26baa'; SS='5713f1fffdea8e56dd6f0242a4c247c7b4ae7659'; SSTREE='1b30eec0f7967f8ad24fab6a55bfaea2ddaec719'
TRAJ='trajectory:36d6a34406f6622eb9ae9abb'; SCHED='schedule:5738127156dbbf561834790e'
START='2026-08-20T03:58:15Z'; OBS='2026-08-20T04:41:45Z'; EARLIEST='2026-08-20T04:58:15Z'; MIN=3600
PRIOR_HEAD='827eed52b965587edd4099dab7badb4741564d85'; PRIOR_WRAP='6bbfd5d0f3d31c297512036abdc8a33056d070ae37872d85cb49788515bdf0f6'; W4N3='ea83cbaf0a20b7e45a0a83680b6f428b8514dc996e54e4e6f00ee6e268631a64'
CEILING='Temporal eligibility control on one existing trajectory only; no qualifying delayed resumption, human repeat-use value, retention, accumulated-history benefit, product direction, network/hosted/market, release, cutover, or owner-admission claim.'

def digest(x): return 'sha256:'+hashlib.sha256(json.dumps(x,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def seal(x,key='content_digest'): y=dict(x); y[key]=digest(y); return y
def write(p,x): p.write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def z(s): return datetime.fromisoformat(s.replace('Z','+00:00'))

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--output',required=True); a=ap.parse_args(); out=Path(a.output); out.mkdir(parents=True,exist_ok=True)
    prior=json.loads(Path('artifacts/gva06/f_ruv/w4/b5/F_RUV_W4_B5_GitHubBranchReceipt.json').read_text())
    elapsed=int((z(OBS)-z(START)).total_seconds()); eligible=elapsed>=MIN
    checks={
      'prior_branch':prior['branch_id']==PRIOR,'target_identity':prior['qualified_target_identity']==TARGET,
      'distinct_return':elapsed>0,'elapsed_frozen':elapsed==2610,'minimum_delay_not_reached':not eligible,
      'no_human_imputation':True,'product_frozen':True,'pointer_slim':True}
    ok=all(checks.values()); terminal='RIGHT_CENSORED' if ok else 'REPAIR_REQUIRED'; first='MINIMUM_DELAY_WINDOW_NOT_REACHED' if ok else 'TEMPORAL_CONTROL_FAILURE'
    obs=seal({'schema_version':'gva06.f.ruv.early-return-observation.v1','artifact_id':'EarlyReturnObservation.v1','program_id':PROGRAM,'wave_id':WAVE,'branch_id':BRANCH,'prior_branch_id':PRIOR,'trajectory_id':TRAJ,'schedule_id':SCHED,'preregistered_at':START,'observed_return_at':OBS,'elapsed_seconds':elapsed,'minimum_delay_seconds':MIN,'remaining_seconds_at_observation':max(0,MIN-elapsed),'earliest_eligible_at':EARLIEST,'distinct_user_initiated_return_observed':True,'eligible_resumption_episode':eligible,'observation_class':'EARLY_RETURN_PRE_WINDOW','raw_user_text_stored':False,'human_judgment_capture_consented':False,'human_judgments':None,'claim_ceiling':CEILING})
    term=seal({'schema_version':'gva06.f.ruv.interrupted-delayed-resumption-trajectory.v2','artifact_id':'InterruptedDelayedResumptionTrajectory.v2','artifact_state':'EXECUTED_VALIDATED_MERGEABLE_CANDIDATE' if ok else 'EXECUTED_REPAIR_REQUIRED','program_id':PROGRAM,'wave_id':WAVE,'branch_id':BRANCH,'prior_branch_id':PRIOR,'trajectory_id':TRAJ,'schedule_ref':SCHED,'qualified_target_identity':TARGET,'qualified_target_tree_digest':TREE,'qualified_target_archive_sha256':ARCHIVE,'existing_eligible_episode_ids':[TRAJ+':episode:001'],'new_eligible_resumption_episode_ids':[],'early_return_observation_refs':[obs['content_digest']],'distinct_user_initiated_return_observed':True,'qualifying_interruption_observed':eligible,'delayed_resumption_observed':False,'resumption_episode_count':0,'terminal_disposition':terminal,'first_zero':first,'human_value_supported':False,'repeat_use_value_supported':False,'accumulated_history_benefit_supported':False,'wave_5_eligible_mechanism':None,'product_direction':'FROZEN','merge_destination':'F.RUV.W4C.RollingSynthesis','checks':checks,'exact_reentry':'On a distinct user-initiated return at or after '+EARLIEST+', bind the same trajectory, schedule and target; append one prospective resumption episode; rerun F.RUV.W4C.B5 before the next Wave-4 N3.','claim_ceiling':CEILING},'artifact_digest')
    pointers=seal({'schema_version':'gva06.f.ruv.w4c-b5-source-pointers.v1','program_id':PROGRAM,'wave_id':WAVE,'branch_id':BRANCH,'stewardstack_commit':SS,'stewardstack_route_tree':SSTREE,'route_launch_digest':ROUTE,'wave4_n3_sha256':W4N3,'prior_branch_head':PRIOR_HEAD,'prior_wrapper_sha256':PRIOR_WRAP,'prior_branch_receipt_digest':prior['content_digest'],'qualified_target_identity':TARGET,'qualified_target_tree_digest':TREE,'qualified_target_archive_sha256':ARCHIVE,'trajectory_id':TRAJ,'schedule_id':SCHED,'prior_payload_bytes_embedded':0,'raw_user_text_embedded':False})
    wr=[]
    specs=[('W1_ROUTE_CURRENTNESS','PASS',{'target':TARGET,'prior_head':PRIOR_HEAD}),('W2_TEMPORAL_ELIGIBILITY','PASS',{'elapsed_seconds':elapsed,'minimum_delay_seconds':MIN,'eligible':eligible}),('W3_CLAIM_CONSENT','PASS',{'human_value_supported':False,'product_direction':'FROZEN'}),('W4_DURABILITY_PACKAGING','PASS',{'prior_payload_bytes_embedded':0,'forbidden_bulk':0})]
    for wid,status,facts in specs: wr.append(seal({'schema_version':'stewardstack.local.worker-return.v1','worker_id':wid,'branch_id':BRANCH,'status':status,'validation_facts':facts,'claim_boundary':CEILING}))
    br=seal({'schema_version':'stewardstack.web.branch-return.v1','branch_identity':BRANCH,'artifact_state':term['artifact_state'],'inputs_consumed':['F.RUV.W4 N3@sha256:'+W4N3,PRIOR+'@'+PRIOR_HEAD,'wrapper:sha256:'+PRIOR_WRAP,TARGET,TRAJ,SCHED],'work_performed':['bound W4C.B5 continuation','verified prior trajectory/target pointers','recorded one distinct early return without raw text','applied frozen one-hour gate','refused eligible episode and human-value promotion','prepared pointer-slim durability return'],'material_outputs':['InterruptedDelayedResumptionTrajectory.v2.json','EarlyReturnObservation.v1.json','WorkerReturn.W1.json','WorkerReturn.W2.json','WorkerReturn.W3.json','WorkerReturn.W4.json','BranchCompletionReceipt.json','NoLearningConsequence.json','GitHubExecutionReceipt.json','SOURCE_POINTERS.json'],'terminal_object':'InterruptedDelayedResumptionTrajectory.v2','terminal_disposition':terminal,'first_zero':first,'completion_predicate_result':'PASS' if ok else 'REPAIR_REQUIRED','validation_or_review':{'temporal_checks':'PASS_'+str(sum(checks.values()))+'_OF_'+str(len(checks)),'elapsed_seconds':elapsed,'minimum_delay_seconds':MIN,'eligible_resumption_episode':eligible,'target_mutation':False,'human_value_supported':False},'claim_updates':{'supported':['distinct return observed before minimum delay'],'unsupported':['qualifying delayed resumption','human repeat-use value','retention','accumulated-history benefit','product direction']},'merge_payload':{'destination':'F.RUV.W4C.RollingSynthesis','trajectory_id':TRAJ,'terminal_artifact_digest':term['artifact_digest'],'early_return_observation_digest':obs['content_digest'],'wave_5_eligible_mechanism':None},'blockers_and_reentry':term['exact_reentry'],'execution_posture':'TEMPORAL_ELIGIBILITY_CONTROL_WITH_GITHUB_DURABILITY','authorization_basis':'Explicit user request for current next-wave branch 5; no broader human-judgment/research consent inferred.','learning_or_no_learning_consequence':'NoLearningConsequence.json','claim_boundary':CEILING})
    completion=seal({'schema_version':'stewardstack.web.branch-completion-receipt.v1','program_id':PROGRAM,'wave_id':WAVE,'branch_id':BRANCH,'route_launch_digest':ROUTE,'target_identity':TARGET,'terminal_object':'InterruptedDelayedResumptionTrajectory.v2','terminal_artifact_digest':term['artifact_digest'],'terminal_disposition':terminal,'first_zero':first,'completion_predicate_result':'PASS' if ok else 'REPAIR_REQUIRED','completion_basis':'Distinct return evaluated against frozen temporal gate and lawfully censored before one hour; no resumption episode or human-value claim manufactured.','accepted_current':ok,'merge_authority_effect':'none_pending_w4c_web_synthesize_and_web_steer','claim_boundary':CEILING})
    nolearn=seal({'schema_version':'stewardstack.learning.no-learning-consequence.v1','kind':'NoLearningConsequence','program_id':PROGRAM,'wave_id':WAVE,'branch_id':BRANCH,'policy_or_model_updated':False,'accepted_human_value_state_mutated':False,'product_direction_changed':False,'reason':'Observed return preceded the minimum delay; no eligible resumption episode or human outcome exists.','frontier_consequence':['temporal attempt recorded','trajectory remains open','Wave 5 remains closed from this branch'],'exact_reentry':term['exact_reentry'],'claim_boundary':CEILING})
    gh=seal({'schema_version':'gva06.f.ruv.w4c-b5.github-execution-receipt.v1','program_id':PROGRAM,'wave_id':WAVE,'branch_id':BRANCH,'repository':os.getenv('GITHUB_REPOSITORY','pakkinlau/ProjectionWorkbench'),'head_sha':os.getenv('GITHUB_SHA','LOCAL'),'branch_ref':os.getenv('GITHUB_REF_NAME','LOCAL'),'workflow_run_id':os.getenv('GITHUB_RUN_ID'),'prior_branch_head':PRIOR_HEAD,'terminal_disposition':terminal,'completion_predicate_result':'PASS' if ok else 'REPAIR_REQUIRED','pointer_slim':True,'prior_payload_bytes_embedded':0,'claim_ceiling':CEILING})
    objs={'EarlyReturnObservation.v1.json':obs,'InterruptedDelayedResumptionTrajectory.v2.json':term,'SOURCE_POINTERS.json':pointers,'BranchReturn.json':br,'BranchCompletionReceipt.json':completion,'NoLearningConsequence.json':nolearn,'GitHubExecutionReceipt.json':gh}
    objs.update({f'WorkerReturn.W{i+1}.json':x for i,x in enumerate(wr)})
    for n,x in objs.items(): write(out/n,x)
    manifest={'schema_version':'gva06.f.ruv.pointer-slim-n2b-manifest.v1','program_id':PROGRAM,'wave_id':WAVE,'branch_id':BRANCH,'terminal_disposition':terminal,'pointer_slim':True,'forbidden_bulk':{'prior_wave_archives':0,'prior_branch_wrappers':0,'qualified_target_archives':0,'repository_snapshots':0,'virtual_environments':0,'dependency_trees':0,'wheels':0,'caches':0,'raw_user_text':0},'claim_ceiling':CEILING}; write(out/'MANIFEST.json',manifest)
    sums=[]
    for p in sorted(x for x in out.iterdir() if x.is_file() and x.name!='SHA256SUMS'): sums.append(hashlib.sha256(p.read_bytes()).hexdigest()+'  '+p.name)
    (out/'SHA256SUMS').write_text('\n'.join(sums)+'\n')
    print(json.dumps({'branch_id':BRANCH,'terminal':terminal,'first_zero':first,'checks':str(sum(checks.values()))+'/'+str(len(checks)),'elapsed_seconds':elapsed,'eligible_resumption_episode':eligible,'wave_5_open':False},sort_keys=True))
    return 0 if ok else 1
if __name__=='__main__': raise SystemExit(main())
